# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.6.3"

# Faz a instalação com Sudo, para ter privilégio de Super Usuário.
#sudo: required

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install flask

# Defini o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - python test.py

# Defini que o processo de Deploy será na Plataforma Heroku. É necessário informar o nome da APP criada no Heroku
deploy:
  strategy: api
  provider: heroku
  api_key: 
    secure: EzjTe3f8iT7q51CRW8zkdNwrvNZ/KgIaENWjkFcayuGpCmdkRmqO7EyNyhWQBLtlaVLF/pgxUpKrZM1kO8OTyZBQ/v4qUXpKeKCS1DzLVyemiEL6hGRWcDl62wci91MevSD89nXBrnXR0zTrFf3d3XugwnP/3e3JCcIl+rxDw446F2wSkro3BWEp7WOm2hshN3IBaQYmdO9/SOqa29YWYN7mD82bnqazAF+Sgfbsy+hyQP/t1Gs7CLfiqw5+oErgt1xMkCUllGImhfJdMkMMuwtb4DNgY+hdHAFzjJ9S4JfZFHecUlPA+rleV8ispQaoSf24zRv2BlIAPCU6OoYX59h4Wa0w/dWXTAQ8JZRWCZYvaXudNA4KDrMfXlogSJS2L75AY3zehrDy91KEcPBpuzC2eEsmCvakND4laBX/Z79TFnsbN+vNige4iiWkxLUoaOrK6qu022eYGcROzdC1rAU8VB9bUaYewgcO0kyNh4rWUVCGHmzdTnp9c/ou6wA9HkSniaN6BI/Yk4KP4pm6sbu8OfzxKvmE4VLzdNzWRW9Ef5rqvj97cvV8lfp2PVv11zuvSPgnObJKXflscSCejH2gICqgQYrorBHYz1vpd5X8dsYrXGBBFGRxE2e9P3xy2BsHDfEJ0+c8HyFOBzbXuId3GTkSj+/MkG/BRYJepeE=
  app: silva-andrre-devopsessentials
